config/routes.rb
Rails.application.routes.draw do
  resources :steward_page_widgets
  resources :steward_kpis do
    member do
      get :test_run
    end
  end
  resource :nav_tree, only: [:show]

  root to: 'visitors#index'
end

app/models/steward_kpi.rb
# == Schema Information
#
# Table name: steward_kpis
#
#  id         :integer          not null, primary key
#  code       :text
#  resource   :string(255)
#  code_type  :integer
#  query_plan :integer
#  position   :integer
#  ancestry   :string(255)
#  created_at :datetime
#  updated_at :datetime
#  node_type  :integer
#  labels     :text
#

class StewardKpi < ActiveRecord::Base
  enum code_type: [:sql, :code]
  enum query_plan: [:realtime, :cached]
  enum node_type: [:category, :kpi]

  has_ancestry
  has_many :steward_page_widgets
  accepts_nested_attributes_for :steward_page_widgets, allow_destroy: true

  #default_scope { order(:position) }

  def self.to_nav_tree
    [].tap do |nav_tree|
      self.roots.each do |r|
        subtree = { label: r.resource }
        self.depth_first_iteration(r, subtree)
        nav_tree << subtree
      end
    end
  end

  def self.depth_first_iteration(node, hash)
    return unless node.has_children?
    node.children.each do |c|

      subtree = { label: c.resource, data: { url: "http://localhost:3000/steward_kpis/#{c.id}" } }
      unless c.has_children?
        subtree[:data][:controls] = c.steward_page_widgets.map do |spw|
          {
            label: spw.label,
            type: spw.widget_type,
            options: spw.options.split(', ').map{|h| h1,h2 = h.split(':'); {h1.strip => h2.strip}}.reduce(:merge),
            name: spw.name
          }
        end
      end
      hash[:children] ||= []
      hash[:children] << subtree
      self.depth_first_iteration(c, subtree)
    end
  end

  def generate_plan(query_params)
    self.code % query_params
  end

  def test_run
    test_params = Hash[*self.steward_page_widgets.map{|spw| [spw.label, spw.options.split(/\W+/)[0]]}.flatten]
    test_params.symbolize_keys!
    begin
      sql_statement = generate_plan(test_params)
      res = Conn.query(sql_statement.sub(/limit \d+/, "LIMIT 1"))
      [true, "SQL statement:  [ #{sql_statement} ] passed, results are [#{res.inspect}]"]
    rescue Mysql2::Error => e
      [false,
       "SQL Error:  [ #{sql_statement} ] Error:  "  + e.message]
    rescue Exception => e
      [false,
       "Error:  "  + e.message]
    end
  end

  def query_kpi_data(query_params)
    logger.info query_params
    logger.info self.code

    data_labels = self.labels.split(', ')
    results = Conn.query(generate_plan(query_params))
    datasets = results.each(as: :array).each_with_index.map do |data, i|
      {label: data_labels[i], data: data}
    end
    return { labels: results.fields, datasets: datasets }
    # return { labels:['test1', 'test2', 'test3'], datasets:[{label: "label 1", data: [3,3,4]}, {label: "label 2", data: [2,3,4]}]}
  end

  def is_kpi?
    self.node_type.to_sym == :kpi
  end

end

app/models/steward_page_widget.rb
# == Schema Information
#
# Table name: steward_page_widgets
#
#  id             :integer          not null, primary key
#  widget_type    :integer
#  label          :string(255)
#  options        :text
#  steward_kpi_id :integer
#  name           :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

class StewardPageWidget < ActiveRecord::Base
  belongs_to :steward_kpi
  enum widget_type: [:dropdown, :text, :radio, :checkbox]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = 'GET, OPTIONS, HEAD'
    headers['Access-Control-Allow-Headers'] = 'x-requested-with,Content-Type, Authorization'
  end
end

app/controllers/nav_trees_controller.rb
class NavTreesController < ApplicationController
  def show
    render json: StewardKpi.to_nav_tree
  end
end

app/controllers/steward_kpis_controller.rb
class StewardKpisController < ApplicationController
  before_action :set_steward_kpi, only: [:edit, :update, :destroy, :show, :test_run]

  # GET /steward_kpis
  # GET /steward_kpis.json
  def index
    if params[:parent_id].present?
      @steward_kpis = StewardKpi.find(params[:parent_id]).children
      @parent_id = params[:parent_id]
      @parent = StewardKpi.find(params[:parent_id])
    else
      @steward_kpis = StewardKpi.roots
    end
  end

  # GET /steward_kpis/new
  def new
    @steward_kpi = StewardKpi.new()
    @parent_id = params[:parent_id]
  end

  # GET /steward_kpis/1/edit
  def edit
  end

  def show
    render json: @steward_kpi.query_kpi_data(JSON.parse(params[:query]).symbolize_keys)
  end

  def test_run
    erorr, msg = @steward_kpi.test_run
    respond_to do |format|
      format.json { render :json => {msg: msg, erorr: erorr} }
    end
  end

  # POST /steward_kpis
  # POST /steward_kpis.json
  def create
    if params[:steward_kpi][:parent_id].present?
      steward_kpi = StewardKpi.find(params[:steward_kpi][:parent_id]).children
    else
      steward_kpi = StewardKpi
    end
    @steward_kpi = steward_kpi.new(steward_kpi_params)

    respond_to do |format|
      if @steward_kpi.save
        format.html { redirect_to steward_kpis_path(parent_id: @steward_kpi.parent_id), notice: 'Steward kpi was successfully created.' }
        format.json { render :show, status: :created, location: @steward_kpi }
      else
        format.html { render :new }
        format.json { render json: @steward_kpi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steward_kpis/1
  # PATCH/PUT /steward_kpis/1.json
  def update
    respond_to do |format|
      if @steward_kpi.update(steward_kpi_params)
        format.html { redirect_to steward_kpis_path(parent_id: @steward_kpi.parent_id), notice: 'Steward kpi was successfully updated.' }
        format.json { render :show, status: :ok, location: @steward_kpi }
      else
        format.html { render :edit }
        format.json { render json: @steward_kpi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steward_kpis/1
  # DELETE /steward_kpis/1.json
  def destroy
    @steward_kpi.destroy
    respond_to do |format|
      format.html { redirect_to steward_kpis_url, notice: 'Steward kpi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_steward_kpi
      @steward_kpi = StewardKpi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def steward_kpi_params
      params.require(:steward_kpi).permit(:code, :resource, :code_type, :query_plan, :position, :ancestry, :node_type, :labels,
        steward_page_widgets_attributes: [:id, :widget_type, :label, :options, :name, :_destroy])
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nav_tree_helper.rb
module NavTreeHelper
end

app/helpers/steward_kpis_helper.rb
module StewardKpisHelper
end

app/helpers/steward_page_widgets_helper.rb
module StewardPageWidgetsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
      = link_to 'Manage KPIs', steward_kpis_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Steward'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Steward'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/steward_kpis/_form.html.haml
= simple_nested_form_for @steward_kpi do |f|
  = f.input :parent_id, :as => :hidden, :input_html => { :value => @parent_id }
  = f.input :resource, :required => true, :autofocus => true

  - if @steward_kpi.new_record?
    .btn-group.node-type{ "data-toggle" => "buttons" }
      %label.btn.btn-default.active
        %input{ 'type' => "radio", 'name' => "steward_kpi[node_type]", 'autocomplete' => "off", 'checked' => '', 'value' => 'kpi'}
          KPI
      %label.btn.btn-default
        %input{ 'type' => "radio", 'name' => "steward_kpi[node_type]", 'autocomplete' => "off", 'value' => 'category'}
          CATEGORY

  - if @steward_kpi.new_record? or @steward_kpi.is_kpi?
    #kpi-params-block
      = f.input :labels, :required => false
      = f.input :code, as: :text, :required => false

      = f.fields_for :steward_page_widgets, html: { class: 'container' } do |spw_form|
        .row
          = spw_form.input :label, wrapper_html: { class: 'col-sm-6' }
          = spw_form.input :name, wrapper_html: { class: 'col-sm-6' }
        .row
          = spw_form.input :options, wrapper_html: { class: 'col-sm-6' }
          = spw_form.input :widget_type, as: :select, collection: StewardPageWidget.widget_types.keys, wrapper_html: { class: 'col-sm-6' }
        = spw_form.link_to_remove "Remove the control", class: 'btn btn-danger btn-sm remove-control-btn pull-right'
        .clearfix
      %p
      = f.link_to_add "Add a page Control", :steward_page_widgets, class: 'btn btn-success add-control-btn'

  = f.button :submit, "Save", class: 'pull-left'

- if @steward_kpi.persisted?
  = button_tag "Test Run", data: { url: test_run_steward_kpi_path(@steward_kpi) }, class: "btn btn-default", id: "test_run_btn"
#test_run_info_area.well

:coffee
  myCodeMirror = CodeMirror.fromTextArea $('#steward_kpi_code')[0],
    lineNumbers: true
    matchBrackets: true

app/views/steward_kpis/edit.html.haml
%h1 Editing steward_kpi

= render 'form'

= link_to 'Back', steward_kpis_path, class: 'btn btn-info pull-right'

app/views/steward_kpis/index.html.haml
%h1 Listing steward_kpis

- if @parent_id
  - @parent.path.each do |sk|
    = link_to sk.resource, steward_kpis_path(parent_id: sk.id)
    >
%table.table.table-bordered
  %tr
    %th Resource
    %th Type
    %th
    %th

  - @steward_kpis.each do |steward_kpi|
    %tr
      %td= link_to steward_kpi.resource, steward_kpi.is_kpi? ? edit_steward_kpi_path(steward_kpi) : steward_kpis_path(parent_id: steward_kpi.id)
      %td= steward_kpi.has_children? ? 'Category' : 'KPI'
      %td= link_to 'Edit', edit_steward_kpi_path(steward_kpi)
      %td= link_to 'Destroy', steward_kpi, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Steward kpi', new_steward_kpi_path(parent_id: @parent_id), class: 'btn btn-success'

app/views/steward_kpis/new.html.haml
%h1 New steward_kpi


.clearfix

= render 'form'

= link_to 'Back', steward_kpis_path, class: 'btn btn-info pull-right'

app/views/steward_kpis/show.html.haml
%p#notice= notice

%p
  %b Code:
  = @steward_kpi.code
%p
  %b Resource:
  = @steward_kpi.resource
%p
  %b Code type:
  = @steward_kpi.code_type
%p
  %b Query plan:
  = @steward_kpi.query_plan
%p
  %b Position:
  = @steward_kpi.position
%p
  %b Ancestry:
  = @steward_kpi.ancestry

= link_to 'Edit', edit_steward_kpi_path(@steward_kpi)
\|
= link_to 'Back', steward_kpis_path

app/views/steward_page_widgets/_form.html.haml
= simple_form_for(@steward_page_widget) do |f|
  = f.error_notification

  .form-inputs
    = f.input :widget_type
    = f.input :label
    = f.input :options
    = f.association :steward_kpi
    = f.input :param

  .form-actions
    = f.button :submit

app/views/steward_page_widgets/edit.html.haml
%h1 Editing steward_page_widget

= render 'form'

= link_to 'Show', @steward_page_widget
\|
= link_to 'Back', steward_page_widgets_path

app/views/steward_page_widgets/index.html.haml
%h1 Listing steward_page_widgets

%table
  %tr
    %th Widget type
    %th Label
    %th Options
    %th Steward kpi
    %th Param
    %th
    %th
    %th

  - @steward_page_widgets.each do |steward_page_widget|
    %tr
      %td= steward_page_widget.widget_type
      %td= steward_page_widget.label
      %td= steward_page_widget.options
      %td= steward_page_widget.steward_kpi
      %td= steward_page_widget.param
      %td= link_to 'Show', steward_page_widget
      %td= link_to 'Edit', edit_steward_page_widget_path(steward_page_widget)
      %td= link_to 'Destroy', steward_page_widget, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Steward page widget', new_steward_page_widget_path

app/views/steward_page_widgets/new.html.haml
%h1 New steward_page_widget

= render 'form'

= link_to 'Back', steward_page_widgets_path

app/views/steward_page_widgets/show.html.haml
%p#notice= notice

%p
  %b Widget type:
  = @steward_page_widget.widget_type
%p
  %b Label:
  = @steward_page_widget.label
%p
  %b Options:
  = @steward_page_widget.options
%p
  %b Steward kpi:
  = @steward_page_widget.steward_kpi
%p
  %b Param:
  = @steward_page_widget.param

= link_to 'Edit', edit_steward_page_widget_path(@steward_page_widget)
\|
= link_to 'Back', steward_page_widgets_path

app/views/visitors/index.html.erb
<h3>Welcome</h3>